---
collections:
  - name: community.general
    version: 13.1.0
  - name: ansible.windows
    version: 3.5.0
  - name: chocolatey.chocolatey
    version: 1.6.0
roles:
  - name: pluggero.rustup
    version: 1.6.0
